spring.application.name=fabric
spring.datasource.url=jdbc:postgresql://localhost:5432/fabric_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
server.error.include-stacktrace=never

# File storage configuration
app.file.storage.path=./storage