spring.application.name=fabric
spring.datasource.url=jdbc:postgresql://db.ftgptrqagwqinbgzyxdu.supabase.co:5432/postgres?user=postgres&password=${DB_PASSWORD}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
server.error.include-stacktrace=never

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# File storage
app.file.storage.path=./storage
